# Autogenerated by Sencha, Inc. on: 14-Sep-2016 01:33:33
#FROM openjdk:8-jre-alpine
FROM openjdk:8-jre

ARG SENCHACMD_VERSION=7.4.0.39

COPY entrypoint.sh /

RUN sed -i 's/http/https/g' /etc/apt/sources.list && apt update && apt install -y libfreetype6 ruby tzdata ttf-dejavu unzip fontconfig wget curl

RUN wget https://cdn.sencha.com/cmd/$SENCHACMD_VERSION/no-jre/SenchaCmd-$SENCHACMD_VERSION-linux-amd64.sh.zip -O senchacmd.zip && \
  echo "Expanding senchacmd.zip" && unzip senchacmd.zip && rm senchacmd.zip && chmod +x SenchaCmd-$SENCHACMD_VERSION-linux-amd64.sh && \
  echo "Installing sencha" && ./SenchaCmd-$SENCHACMD_VERSION-linux-amd64.sh -q -dir /opt/Sencha/Cmd/$SENCHACMD_VERSION -Dall=true && \
  rm SenchaCmd-$SENCHACMD_VERSION-linux-amd64.sh && chmod +x /opt/Sencha/Cmd/$SENCHACMD_VERSION/sencha && \
  sed -i "s/http/https/g" "/opt/Sencha/Cmd/$SENCHACMD_VERSION/templates/repo/{senchadir}/repo/remotes/sencha/sencha.cfg" && \
  chmod +x /entrypoint.sh 

EXPOSE 1841

ENV PATH="/opt/Sencha/Cmd/$SENCHACMD_VERSION:${PATH}"

ENTRYPOINT ["/entrypoint.sh"]

CMD ["help"]