name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push 7.4.0.39
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            SENCHACMD_VERSION=7.4.0.39
          tags: fvoncina/docker-sencha-cmd:7.4.0.39,fvoncina/docker-sencha-cmd:latest
      
      - name: Build and push 7.3.0.19
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true          
          build-args: |
            SENCHACMD_VERSION=7.3.0.19
          tags: fvoncina/docker-sencha-cmd:7.3.0.19

      - name: Build and push 7.2.0.66
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            SENCHACMD_VERSION=7.2.0.66          
          tags: fvoncina/docker-sencha-cmd:7.2.0.66  
      
      - name: Build and push 7.1.0.15
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            SENCHACMD_VERSION=7.1.0.15          
          tags: fvoncina/docker-sencha-cmd:7.1.0.15
      
      - name: Build and push 7.0.0.40
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            SENCHACMD_VERSION=7.0.0.40          
          tags: fvoncina/docker-sencha-cmd:7.0.0.40
      
      - name: Build and push 6.7.0.63
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            SENCHACMD_VERSION=6.7.0.63          
          tags: fvoncina/docker-sencha-cmd:6.7.0.63
      
      - name: Build and push 6.6.0.13
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            SENCHACMD_VERSION=6.6.0.13          
          tags: fvoncina/docker-sencha-cmd:6.6.0.13
      
      - name: Build and push 6.5.3.6
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            SENCHACMD_VERSION=6.5.3.6          
          tags: fvoncina/docker-sencha-cmd:6.5.3.6