name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file ./7.2.0.66/Dockerfile --tag fvoncina/docker-sencha-cmd:7.2.0.66 ./7.2.0.66
      
